[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msiconvert"
version = "0.1.0"
description = "A library to convert MSI data into different formats"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "zarr",
    "dask",
    "scipy",
    "pyimzml",
    "tqdm",
    "spatialdata",
    "anndata",
    "geopandas",
    "shapely",
]

[project.scripts]
msiconvert = "msiconvert.__main__:main"
